### ISSUE TITLE
Find a solution to implement Railcraft-Features for our Tracks

### ISSUE THREAD

**Issue by NitroxydeX** [EternalBlueFlame/Traincraft-5#102]
This is something we need to talk with @CovertJaguar since the Railcraft API only checks for instances of BlockRailBase. And I don't think we can parse anything from TC to it.
- [ ] Implement Signals
- [ ] Implement Switches

**Comment by EternalBlueFlame** [comment]
It's possible that it could be handled through the TCRail block without having to get modifications in an unsupported version of railcraft specifically for supporting TC.
We already have to check for redstone signals, the railcraft signals should be able to be dealt with in a similar way.

**Comment by CovertJaguar** [comment]
Hmm...getting your switches to respond to my Switch Actuators should be simple enough, if that is what you mean. See ISwitchDevice in the API. The first parameter of shouldSwitch() can actually be null, nothing uses it since the last switch rewrite. I will warn you that the track itself does most of the fancy logic regarding where to find carts and when to ask the Actuators if it should switch for a specific cart, this would need to be handled on your end.

Getting the Actuators signage to indicate the proper directions is a little tricker but I can make that easier when I reimplement the switches for 1.10. It's just cosmetic anyway.

Interfacing with the wireless controller/receiver network should be fairly trivial if that is something you desire.

Regarding the Block Signals, cart/track detection is going to be much more difficult to do anything useful with. I doubt it would be possible to retrofit anything related to cart detection onto 1.7. It actually walks the tracks to determine if the signal block is valid, I don't see this easily translating to non-standard tracks.

Going forward into 1.10, one of the things high on my todo list is implementing Token Signals, which should largely not care about tracks, only whether carts pass beneath the signal. It should be trivially possible to insert some kind of handler for cart searching into that.
