### ISSUE TITLE
Trains and slopes.

### ISSUE THREAD

**Issue by Larky2k** [EternalBlueFlame/Traincraft-5#131]
Using the latest download. Trains randomly will do a 180° on slope and stop moving. Happened once but can't reproduce.

**Comment by NitroxydeX** [comment]
This shouldn't happen. Tested it an hour with highspeed train. No Problems.

**Comment by Larky2k** [comment]
when it happened i was using the shay and was going slowly. Will see if i can reproduce.

**Comment by Czarified** [comment]
I remember getting this bug a lot in 1.6.4, or at least something similar. Larger engines would visually flip around if they went too fast around a vanilla corner. Try going around a vanilla corner track piece in the biggest steam engine at a reasonable speed.

From what I remember, the bug was only visual and you could still drive your loco just fine, it just looked backwards.

**Comment by Larky2k** [comment]
Well playing some more and hasn't happened again. But i have found when Trains are going up or down on a long slope. The Train see-saws when trans-versing it and also when a train hits a low hanging object it does do a complete 180 but still be attached. 
Final thing I'v noticed if the train is going really really really slowly so speed is showing 0 but the train in very slowly moving  the train and cars will do a 90 degree turn on turns so they are sideways but when speeds up go back to normal. Having a guess the rotation does kick in due to such slow speed.

**Comment by NitroxydeX** [comment]
@Larky2k that is because of the hitboxes since 1.6.4
