### ISSUE TITLE
Few weird things about TC tracks.

### ISSUE THREAD

**Issue by MarioPL98** [EternalBlueFlame/Traincraft-5#163]
Hi. I noticed some weird things about TC tracks.
1. Is this normal that render distance of those tracks is very short? (like 90 blocks on far or something like that)
2. Wouldn't be better if for example crafting M straight tracks would give 1 track instead of 2? Same with L rails but with a bit different recipe? It's similar thing with other types of tracks.
3. What about cobblestone/stone slope rails? Or rather I should ask: Why only those 3?

Thanks for answers.

**Comment by NitroxydeX** [comment]
Hello Mario,
1. yes it is normal that it's a very short distance. Go into creative flat world and place as many rails you can around you. You will see that your FPS is dropping really fast downwards. That's the reason why we do render really short that performance isn't affected too much. It's also the reason why we tell the users to use as many vanilla or Railcraft rails they can (Since I changed the positioning on MC/RC Tracks to be the same as on TC tracks)
2. The recipes are carried from the old TC but I agree that they are kinda bad. It's like cheating on yourself when using e.g. Long Straights. I will redo most of them to better fit them to each other.
3. You ever saw Cobblestone or stone slopes in reallife? No? Well, thats the reason. The Trains always got Ballast-railbeds. Thats why we implemented it. We use Gravel too because most users are using Gravel under their rails. The Wood one is carried from 1.6.4. It's to extend the bridgeblocks they they are used to build a bridge which I would never recommend anyway.

**Comment by MarioPL98** [comment]
Thanks for super quick reply.
1. Oh, I see performance dropping a bit. It's caused by 3D model of rails, am I right?
2. When can we expect some update about this? I'm creating modpack for me and my friends and we are like http://i.imgur.com/IaLG69W.gif XD
3. You are right there but don't forget that it's Minecraft. It's like "you ever saw floating dirt in reallife?". Whole game is over-simplified and made to be funny not realistic.

**Comment by NitroxydeX** [comment]
Hello Mario, 
no problem. You will always see one of us is answering questions here. We're around the world and shake the others hands when standing up/going to bed.
1. Yeah correct. 3D-Rendering in Minecraft always takes massive performance.
2. I'm redoing the recipes at the moment. Update. Between 1 and 7 Days for a new Version.
3. Thats true. But even if TC is more like Aracde Trainstuff thats something we won't change atm.

**Comment by MarioPL98** [comment]
Thanks!

**Comment by MarioPL98** [comment]
BTW I can't find out how to change manually slope tracks. Is there any lever for it?

**Comment by NitroxydeX** [comment]
@MarioPL98 What you mean by "change manually slope tracks"?

**Comment by MarioPL98** [comment]
Change direction where I want to go.

**Comment by NitroxydeX** [comment]
I may not understand what you're trying to do... Can you show some screenshots or videos? Or join our discord so we can talk there.

**Comment by MarioPL98** [comment]
My fault, i meant parallel tracks XD sorry
I feel ashamed now

**Comment by NitroxydeX** [comment]
Well yeah. You need to power it by Redstone. ^^

**Comment by MarioPL98** [comment]
Oh, I was powering it in wrong place before

**Comment by NitroxydeX** [comment]
Closed via 3ed91687a3c65f8bf9098c0dfcafe9d45dfd8b3a and 2068f95747de732f5f73a214c30d35351433bc92

**Comment by MggMuggins** [comment]
Would it be possible to change the track rendering at an appropriate distance so that they could be rendered farther, still look nice, but not be so resource intensive?

**Comment by MarioPL98** [comment]
Maybe if making tracks rendered as 2D after for example 3-4 chunks would be better?

**Comment by MggMuggins** [comment]
Exactly, so that you could still see them, but not be so hard on the machine.

**Comment by NitroxydeX** [comment]
3-4 chunks is a really short distance. But  unfortunately we can't render them in 2D after a while.

**Comment by MarioPL98** [comment]
What about making them render as one block after connecting?

**Comment by NitroxydeX** [comment]
you can't. You have to use Tiles.
