### ISSUE TITLE
How to make BridgePillars less GPU instensive

### ISSUE THREAD

**Issue by MggMuggins** [EternalBlueFlame/Traincraft-5#186]
I didn't call this issue "Laggy Bridge Pillars" for a reason, because I want to be clear that I have a better understanding of what is going on.
Basically, It would be really nice if Bridge pillars did not reduce your FPS from 50 to 7 if there are enough of them in a general area. The way I understand how this happens is that the bridge pillars are a tileentity so that they can use the special renderer. The problem is that tile entities are rendered fresh every frame, so if there are enough of them, they can cause serious lag. I would like to know if there is a way to use cached rendering for these blocks, since they don't need to be re-rendered every frame, and therefore are more flexible in terms of use.

**Comment by EternalBlueFlame** [comment]
The issue is mostly the faulty way (and format) we do tile entity rendering in general. the base game has a number of tile entities (like the lever) that don't cache the render, and dont cause fps drop.
This issue isn't limited to the bridge pillars either, the rails are just as bad, its just less noticible because they aren't 1x1.

The difficult part is that our render code is massive (and a spagetti mess) and would take a long time to improve.

**Comment by MggMuggins** [comment]
Well, now that I'm getting into modding I might take a look at it.

**Comment by EternalBlueFlame** [comment]
I'm making some improvements to various render systems right now but there is almost no code at all for the bridge pillar.
I managed to make some small improvements to it, but I doubt it will net much improvement.

**Comment by EternalBlueFlame** [comment]
Aright, the render lag all around for tile entities, and even trains, shouldn't be as bad with this change.
[https://github.com/EternalBlueFlame/Traincraft-5/commit/ef166e0af0b536747cd653554fb0e01a586e308c](https://github.com/EternalBlueFlame/Traincraft-5/commit/ef166e0af0b536747cd653554fb0e01a586e308c)

**Comment by MggMuggins** [comment]
That's great. One problem I had with TC was that it lagged badly if too many trains were rendered.
