### ISSUE TITLE
Trains aren't moving

### ISSUE THREAD

**Issue by CrazyPuffleGamer** [EternalBlueFlame/Traincraft-5#220]
The fuel is full, the brakes are off, I am using Railcraft and I am on 1.7.10 too (important if it causes and "incompatibility errors". I have both as the 1.7.10 ver.). When i go to press W, nothing happens. So obviously I try the up key. No response. I try using regular rails. Still nothing. So I face forward. No movement, still. So then i am spamming the keyboard. Train=rock. I remove Railcraft. No movement=true. I feel like breaking my computer. I downloaded a mod that dosen't even work!

**Comment by NitroxydeX** [comment]
We need more Information.

Let's go through that:

- We have no problems with Railcraft
- Movement is working on our side
- Trains are working on Vanilla Rails, Railcraft Rails and Traincraft Rails

It seems you left something out. Which train you tried? Steam Trains are auto turned-on if you have coal in it (but don't forget the water otherwise they explode). Diesel and Electric Trains have to be turned on in the GUI.
Steam and Diesel Trains need to have the state "HOT" to drive. Electric Trains don't have states.

Are you having more mods installed?

**Comment by EternalBlueFlame** [comment]
Okay, it's been almost a week. Are you gonna give us anymore information on the issue @CrazyPuffleGamer , or do I just mark this as user error?

**Comment by CrazyPuffleGamer** [comment]
Well... I'm using railcraft and traincraft And the train is on in the gui,
redstone's in, and I'm on 1.7.10. That's all the info I have! I don't have
any more!

**Comment by CrazyPuffleGamer** [comment]
... Look on your earlier reply. Why did you close it? It's not fixed!

**Comment by EternalBlueFlame** [comment]
is it actually consuming the redstone?

**Comment by CrazyPuffleGamer** [comment]
Yes

**Comment by CrazyPuffleGamer** [comment]
I saw a video. There were particles coming out in the vid but on my game there were no particles.

**Comment by CrazyPuffleGamer** [comment]
About the week... Every other week, let's just say I cant use this computer. Please don't ask any questions.

**Comment by CrazyPuffleGamer** [comment]
Hello?

**Comment by EternalBlueFlame** [comment]
did you remember to turn it on?
with diesel and electric trains they have to be switched on before the particle will start and you can use it.

**Comment by CrazyPuffleGamer** [comment]
Yes, it is.

**Comment by CrazyPuffleGamer** [comment]
But no particles

**Comment by CrazyPuffleGamer** [comment]
And I made sure it was on in the GUI

**Comment by EternalBlueFlame** [comment]
in that case it sounds like a desync between client and server... This issue was common with revision 001 and 002, but was fixed in 003 and later, so be sure you are on the latest.

It could also be caused from the server tool like cauldron or spigot (we only support KCauldron and thermos).

If it's in single player that makes the issue even more strange and I would have to take a guess at some form of optimization tool is interfering, or perhaps your java version is well out of date (Traincraft needs at least java 7 rev 45, but works best on java 8).

I know it's not something on our end, I've done extensive testing on all this stuff.

**Comment by CrazyPuffleGamer** [comment]
I have java 7

**Comment by CrazyPuffleGamer** [comment]
32 bits

**Comment by EternalBlueFlame** [comment]
Theoretically that _should_ work. what about the rest of what i mentioned?

**Comment by CrazyPuffleGamer** [comment]
I use Minecraft Forge.

**Comment by CrazyPuffleGamer** [comment]
for 1.7.10

**Comment by CrazyPuffleGamer** [comment]
10.13.4

**Comment by EternalBlueFlame** [comment]
Let me try and be a bit more specific here...

1. What revision of traincraft are you on?
2. Was it single player? and if not, what are you using for server hosting (forge, cauldron, spigot, etc)?

**Comment by CrazyPuffleGamer** [comment]
Revision... I believe... 3???

**Comment by CrazyPuffleGamer** [comment]
or 2?

**Comment by CrazyPuffleGamer** [comment]
or 1?

I never checked!

**Comment by CrazyPuffleGamer** [comment]
4.3.0_003.

Which one is the revision?

**Comment by CrazyPuffleGamer** [comment]
I'm using single player.

**Comment by EternalBlueFlame** [comment]
try updating, it shouldn't happen on 003 but its been a long while so I'm not fully sure.
At this point we're already on revision 5.

**Comment by CrazyPuffleGamer** [comment]
I'll Try a later version. But keep it open. Just in case.

**Comment by CrazyPuffleGamer** [comment]
I just got Revision 5. I'm about to put it in my mods folder!

**Comment by CrazyPuffleGamer** [comment]
WHat? It's not moving!!! What button do you press? I'm using W but if that's not the cause then WHAT IS?

**Comment by CrazyPuffleGamer** [comment]
Whoah! It's the foward key!!! It works!!! Alright have a good night!

**Comment by EternalBlueFlame** [comment]
Glad to hear you got it working.
That was one of the newer features in 004 that you can change the keybinds, so that should help a bit too.
