### ISSUE TITLE
Crash with EX Roller Coaster

### ISSUE THREAD

**Issue by ghost** [EternalBlueFlame/Traincraft-5#255]
first, link for report bellow
[http://pastebin.com/RTvM7STA](http://pastebin.com/RTvM7STA)

in the server, when i right click to get on the train, then i got off by pressing shift,
the server was down. reappearance when single. 
that is critical problem, so could you fix, or tell me avoidance way?

thanks

**Comment by NitroxydeX** [comment]
It's caused by 
`at erc.manager.ERC_CoasterAndRailManager.motionactive(ERC_CoasterAndRailManager.java:205)`
which is "EX Roller Coaster"

**Comment by EternalBlueFlame** [comment]
Nitro is correct, its a null variable where one isn't expected or compensated for.
If I had to guess it's because the rollercoaster mod doesn't expect the player to dismount through the pre-1.6 methods. Which should actually cause issues with a vast number of mods, not just TC.
I'm not even sure if this can be dealt with in the rewrite due to the multi-passenger functionality in it....

It was kind of hard to find but here was the original forum for the mod, it's in japanese, but you can check if there's a newer version than what you are using now (the latest version seems to be 1.4). and if that fails, you can always try posting the error over there, maybe the creator can do something about it.
[http://forum.minecraftuser.jp/viewtopic.php?uid=98630&f=13&t=28387&start=0#p247474](http://forum.minecraftuser.jp/viewtopic.php?uid=98630&f=13&t=28387&start=0#p247474)
