### ISSUE TITLE
Mallard the OP-Train? -->Fixing Solutions

### ISSUE THREAD

**Issue by SuperKingJulian2** [EternalBlueFlame/Traincraft-5#257]
We are all happy about to have a new train in Traincraft finally.... but nobody wants a Train if its Overpowered like the mallard... there are different solutions to fix it...
1st: crafting --> use steel instead of iron parts (also would have to change the table the loco is crafted in!)
2nd: speed and strenght of loco? --> a SD70 / SD40 is only strong 900 mhp? well the mallard is too strong then  (@NitroxydeX is already informed about this and told me SD is not strong enough and will be fixed, i hope there are no other trains which arent powerfull enough if so... well i guess NitroxydeX will also fix these locos) 
3rd: also already mentioned from @NitroxydeX is a new better texture (and what i still hope a little change on size and lenght of the mallard since it seems very small (also if it is not realistic anymore then))

I think thats all for the mallard so far, but really important is the change from iron to steel... because yes this makes it that overpowered!

Your SKJ

**Comment by NitroxydeX** [comment]
The textures I mentioned are for new models of our old trains. not for the mallard. everythings fine with the mallard texture. :)

**Comment by EternalBlueFlame** [comment]
I agree with you SKJ, and personally I'm a bit more biased towards the first option, because when I was adding the train I figured it would be good to make it more expensive since it's a very strong steam locomotive, even in realistic scale to it's real version and TC stats, but I totally forgot about steel parts in the process of adding it.

Item 2, yeah the SD70/40 values need tweaking.

Item 3, I admit the texture is a little bright for the mod, including the icons, they probably should be a bit more gritty. But we gotta rely on contributors for that, I'm not as gifted as Mr. Brutal when it comes to art, all I can provide is the code to make stuff work, most of the people running this project are in the same boat, or close enough, so we have to rely on contributors for art.

**Comment by EternalBlueFlame** [comment]
did some changes to the stats in [https://github.com/EternalBlueFlame/Traincraft-5/commit/5ef3ffab46259539ff3c383dc8cd4a5f1d782209](https://github.com/EternalBlueFlame/Traincraft-5/commit/5ef3ffab46259539ff3c383dc8cd4a5f1d782209)
it's more realistic now i think, but opinions would be great.

**Comment by SuperKingJulian2** [comment]
Seems good so far, now we only need the steel parts instead of iron and mallard is finally a train which is not overpowered xD
thanks alot for your work ;D

**Comment by SuperKingJulian2** [comment]
Seems the train is still out of iron so no change to steel for future?

**Comment by MggMuggins** [comment]
Creating a commit to change a few iron ingots to steel isn't that hard...

**Comment by SuperKingJulian2** [comment]
Love you xD

**Comment by SuperKingJulian2** [comment]
Shouldnt be the Mallard be crafted in TIer II now?
because you have to craft it in tier 1 still and with steelparts it should be at least tier 2 since it still has some iron parts

**Comment by EternalBlueFlame** [comment]
nah its a bug for some reason everything can be crafted in tier 1.
no idea why. looking into it now.

//EDIT, scratch that, it is listed as tier 1 (was supposed to be 2) and we have that crafting glitch. joy of joys. all the bugs.

**Comment by SuperKingJulian2** [comment]
Hoping for a fix in next update :P

**Comment by EternalBlueFlame** [comment]
it appears the tier recipe glitch is a compiler error, no code is actually wrong and my compiles don't reproduce it.
The mallard's tier was changed to tier 2 in a recent update however.
