### ISSUE TITLE
[Enhancement] Recipe to convert minecraft Rails to TC rails

### ISSUE THREAD

**Issue by HadesDurin** [EternalBlueFlame/Traincraft-5#269]
As Title Says, just a simple recipe to convert normal rails to the standart TC rails.

I have several stacks of normal rails and miss a way to convert the rails to enhance the minecraft rails in a way traincraft does it.

**Comment by EternalBlueFlame** [comment]
You know, that's a _really_ good point, the new rails are _really_ expensive, but offer no benefit over the vanilla ones.
I'll rework the recipe for 009.

**Comment by NitroxydeX** [comment]
Our Small Straight is using the same recipe as the basegamerails. A way to convert normal Rails to TC rails could be an idea for the rewrite. in the port it's better to prefer mc rails over TC rails.

But there has to be added steel. (Since our rails are using steel)

**Comment by EternalBlueFlame** [comment]
The steel does effectively make it more expensive than vanilla rails, for no real reason.
And allowing to convert basegame to TC rails is as simple as adding another recipe, which I already did, in the last git push. Although I realized a mistake, I accidentally removed the old recipe rather than making it cheaper, so I gotta add that back now, just, without the steel.

Although it might not be a bad idea for the rewrite to make a recipe in TC for converting TC rails to vanilla rails (I'm pretty much rewriting the vanilla rail's client code, no point in having 2 straight tracks that are exactly the same for everything but render, might as well make a switch for the render).

//EDIT: wait it's a stack of 32...? well crap, that's way cheap. I'll have to fix that...
