### ISSUE TITLE
[Enhancement] Add Fluids to Forge Liquid Dictionary

### ISSUE THREAD

**Issue by HadesDurin** [EternalBlueFlame/Traincraft-5#288]
Add Diesel and Refined Fuel to Forge Liquid Dictionary.
maybe also make refined Fuel equal to Buildcraft Fuel.

**Comment by agonija** [comment]
You can edit this via

https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java

I added Immersive Engineering Diesel a while ago. Maybe you could add this to the next update?

**Comment by EternalBlueFlame** [comment]
according to the code they are already registered in forge's FluidDictionary.
https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java#L56-L57

However The current system doesn't use classes to define the fluids, they are static variables, so we can't properly implement buildcraft's interfaces for fuel to the fluid objects.
There is an attempt at it here, but clearly not a working one anymore due to the required implementations in their API:
https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java#L77-L81
