### ISSUE TITLE
Zeppelin doesn't turn

### ISSUE THREAD

**Issue by EternalBlueFlame** [EternalBlueFlame/Traincraft-5#29]
The graphical update to make the zeppelin rotate in the direction it's going, doesn't seem to happen.
Not sure if it's an issue with the packet, or with processing the data.

**Comment by lehjr** [comment]
Fixed but code could use a good cleaning to git rid of the unused variables. https://github.com/lehjr/Traincraft-5/commit/03dda4595c1dad074bd09d50d656be98943379e6

**Comment by EternalBlueFlame** [comment]
that goes for the entire mod, but having it working takes priority over having it be clean.

As for the fix...
It seems to work, but:
Removing the packet could break the rotation for multiplayer.
Removing the reset to update ticks as you did will create a crash.

Cherry on the cake, you'll still need to make a pull request and sign the CLA if you haven't already, unless this was only meant to be a hint.

**Comment by lehjr** [comment]
I've tried it in multiplayer and it updates on both screens (using fields from Entity helps when they have their own datawatcher). Rotation was never really good to begin with but could probably be improved with a bit of cleaning and using the vanilla boat as a guide since that's where much of the code originally came from. Keybinding is also a mess, always was. 

 I signed the CLA months ago (unless there's a different one) when I pushed the gradlized 1.6.4 source and pushed MrBrutal to adjust the licence since it was flat out incompatible with reality. It's still not great, but compared to its original state, it's not that bad. I did start working on it briefly but ended up being the sole maintainer for Modular Powersuits, so that's kept me pretty busy.

**Comment by EternalBlueFlame** [comment]
Good to know the multiplayer works, and that you actually bothered to test it.
Vanilla boat code would be an improvement to turning, but even that is kinda bleh.
Keybinding needs work in general, we shouldn't be using Keyboard.KEY because that can be absent on some custom servers, creating a crash. (Or so I've been told).

The CLA is the same for all versions (which probably creates legality holes, but the license still contradicts every point it makes, so what's the difference at this point).
