### ISSUE TITLE
High Speed trains no longer couple by the nose

### ISSUE THREAD

**Issue by FloofyPeachy** [EternalBlueFlame/Traincraft-5#292]
Ok, trains coupling by the nose which does is important to me. I run routes that has a set of a train, then they split at a station and go different ways, then coming back couple together. But with these builds in the repo, it does not work. It works for Traincraft-4.3.2_009 stable build, but not this. I don't know why this is happening, I just like to build my own version of Traincraft for personal use.

**Comment by EternalBlueFlame** [comment]
Wait, I'm confused, Traincraft-4.3.2_009 is the latest release. What "new versions" are you talking about?

**Comment by FloofyPeachy** [comment]
Edited.

**Comment by EternalBlueFlame** [comment]
That makes more sense....
Any idea what update broke it?
I'll look over the changes and see where it may have gone wrong, but if you know what exact update did it, that speeds things up.

//edit:
okay, i don't see anything.... one other thought is it might be your IDE setup (or I'm just missing something, which would be anything but a first).
I believe it was this build we used to release 009, maybe give that a go and see if it works? If nothing else it's a good bookmark from where to where the issue is confined..
https://github.com/EternalBlueFlame/Traincraft-5/tree/01f6c86d95d205270ad830ed570df8c2a046b350

**Comment by FloofyPeachy** [comment]
Yep, that one works.

**Comment by EternalBlueFlame** [comment]
I wonder if its the new chunkhandling.....
As far as I know this was the closest change to the issues you are experiencing.
before: https://github.com/EternalBlueFlame/Traincraft-5/tree/691df4cd8a36a532f2d770b2704ec1fe9a153007

after: https://github.com/EternalBlueFlame/Traincraft-5/tree/266f44e7f6c58dbe6d037c7ce710dc7405c3932a
