### ISSUE TITLE
New Coach/Car release : Amfleet

### ISSUE THREAD

**Issue by Valaktik** [EternalBlueFlame/Traincraft-5#294]
Heyllo ! (Is it the right place to post this ?)

Firstly, I want to thank the few great guys who made and still develop TrainCraft ! Love U x)
As I wanted to help, I made a vehicule for the mod ! It is the Amfleet Car which is a common coach is the USA.

[Zip Upload Site](https://www.fichier-zip.com/2017/06/29/amfleetcar/)
(Strangely GitHub won't take the Zip file ... Don't forget to tick you'r not a robot :P)
**NOTE** : java file seems to be a little incorrect ... When I import the java file I just exported, the 3d
model isn't the same ...

![amfleetcarmodel](https://user-images.githubusercontent.com/21008123/27710396-e09b8fa2-5d1f-11e7-8a41-48da842364e0.PNG)
_This is how it looks in the modelling software._

# INFO : 
Weight : 47.0 t
Max Speed : 125 mph, 201 km/h
More on [Wikipedia](https://en.wikipedia.org/wiki/Talk:Amfleet)

I hope it will work fine ! If you have any comment on the model please tell me about it ! I think I still have strength to correct the model ! :]

Happy Training and Signaling !

**Comment by MggMuggins** [comment]
Looks exactly like the ones that go through town every day. Nicely done!

**Comment by NitroxydeX** [comment]
The right place would be #58 but this time we're a bit nicer. :P

**Comment by EternalBlueFlame** [comment]
> NOTE : java file seems to be a little incorrect ... When I import the java file I just exported, the 3d
model isn't the same ...

It wont import correctly because the package and import URI's aren't correct. the render function may also not be called correctly (the last value on call should be 0.065f in most cases)
These are all very minor things that are no effort for me to fix and I don't even expect to be correct. But I would assume you're curious why they don't work.

> (Is it the right place to post this ?)
As nitro said, it's not, but this is worth an exception.

let me get the lead artist in on this....

**Comment by EternalBlueFlame** [comment]
> NOTE : java file seems to be a little incorrect ... When I import the java file I just exported, the 3d
model isn't the same ...

Shape3D is retired in our version of model render turbo, it won't render. Use shapeboxes instead.
It's great to see attempts with contribution though.
There is also a lighting bug, ignore that, it's fixed in some code I haven't uploaded yet.

Beyond that i'll get the lead artist in on this for any more specific critiques (if he has any)

//EDITED, I re-went over the model and saw something I didn't notice at first. So my original reply was removed, sorry if that causes any confusion.
