### ISSUE TITLE
Distill Diesel amount on leaves and sugar cane is really unrealistic

### ISSUE THREAD

**Issue by TheSpareAce** [EternalBlueFlame/Traincraft-5#295]
Could you guys please add diesel buckets, and have them made burnable? 

The Pro's and Con's of this over fuel canisters would be this:

Pro's: Can be used as fuel (for Furnaces, and all other things that require burnable material), and can be placed on the ground.

Con's: Can't stack buckets, unlike fuel canisters, and can't be converted into canisters, unless you have other mods that have tanks.

**Comment by NitroxydeX** [comment]
> and can be placed on the ground

This is not true. A bucket doesn't mean you can place the "liquid" inside it on the ground. Milk is the best example for this. It needs to be done by the mod authors which we won't do because the original authors made it like this.

We define Diesel as a fuel on different mods and register it to the Forge Fluid and FluidContainer registries as you can see here: https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java#L54 and here: https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java#L60

If Buildcraft is available we add it as a fuel source into Buildcrafts Fuel registry and if Railcraft is available we also add it as a BoilerFuel.
https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java#L75
https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java#L81

where do you experience problems with our Diesel canisters?

**Comment by TheSpareAce** [comment]
Where I experience problems is with Immersive Engineering's "Diesel Generator".

(Yes, it seems ironic.)

**Comment by EternalBlueFlame** [comment]
The "bucket" functionality is no different from our current fuel canister. It probably just isn't registered for use with IE. But seeing as you can make it with sugar, that's probably a good thing....

**Comment by TheSpareAce** [comment]
Speaking about making diesel with sugar, I think it should be 0.125% the output of regular petroleum. 1kL/sugar cane seems a bit ludicrous. 

And about the bucket vs canister thing, would you get a canister back from a furnace after burning the diesel in it, like you would with a bucket?

**Comment by NitroxydeX** [comment]
Yeah you will get the Canister back. It's registered too:
https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/api/LiquidManager.java#L60
