### ISSUE TITLE
Rightclick while riding a train

### ISSUE THREAD

**Issue by EzerArch** [EternalBlueFlame/Traincraft-5#314]
We use the rightclick to "mount" a train. Once mounted, the rightclick causes a quick rubber-band as if the player were attempting to mount again inside the wagon or train.

I propose either:
1. Use _**the horse mechanics**_: use rightclick to mount; once in there, the rightclick can be used to eat, drink and put armor on. I'm not sure as to using the bow: it could be disabled or arrows could bounce off the vehicle hitbox, as it does to horses.
2. Disable the rightclick altogether if the player is inside vehicle hitbox. Too extreme?

NitroxydeX Note: edited cause we use rightclick not leftclick

**Comment by NitroxydeX** [comment]
We just need to check if the player is inside a rollingstock and disable rightclick functionality for the entity itself so it should be possible to eat and drink inside the train or even interact with things outside the train like levers.

However the starvation bar is missing if you're inside a train or on a horse. I know this has changed in later Minecraft versions but I don't know if we can get it that easy back since we're relying on minecarts.

**Comment by EternalBlueFlame** [comment]
should be fixed as of
[https://github.com/EternalBlueFlame/Traincraft-5/commit/1d5fd78540620455a6021ed3ed0b6740276d3d40](https://github.com/EternalBlueFlame/Traincraft-5/commit/1d5fd78540620455a6021ed3ed0b6740276d3d40)
