### ISSUE TITLE
Trains not rendered if ColoredLightsCore is installed

### ISSUE THREAD

**Issue by ghost** [EternalBlueFlame/Traincraft-5#334]
This problem exists in Traincraft-4.3.3_011, with high speed locomotive, and some others.
I know that CLC mod is experimental, but it is no longer going to be updated, and Traincraft-4.3.2_009 works fine alongside it.

Ok, right now I can use Traincraft-4.3.2_009, but I'm looking forward for Trains in Motion, and hope that there will be no such problems.

![2017-10-15_13 59 58](https://user-images.githubusercontent.com/32820765/31588022-a147b112-b1f4-11e7-9891-a91df50fe5a1.png)
![2017-10-15_14 00 14](https://user-images.githubusercontent.com/32820765/31588023-a17ae8d4-b1f4-11e7-81bb-c6148e27bb8a.png)
![2017-10-15_14 01 29](https://user-images.githubusercontent.com/32820765/31588024-a1a3ca1a-b1f4-11e7-9ac3-63ec93118361.png)

**Comment by NitroxydeX** [comment]
We're using a new render that could cause the issue. TiM will use the same one. So it could be the same

**Comment by ghost** [comment]
Strangely, A4 mallard renders normally.

![2017-10-15_22 41 08](https://user-images.githubusercontent.com/32820765/31588416-2d19e58e-b1fa-11e7-9407-b9c32eb9a724.png)

**Comment by EternalBlueFlame** [comment]
009 is a pretty old build, and there have been a good number of render changes and fixes since. 
011 or the upcoming 012 might fix it, but likely it's due to a conflict in texture binding because they probably don't do it right.

You can try changing "B:DISABLE_FLICKERING=true" in your TC config, that may fix it. But beyond that this bug is on them.

**Comment by ghost** [comment]
Unfortunately, changing that config didn't helped.

**Comment by NitroxydeX** [comment]
it's strange that it does not effect all trains. Because all of our trains are using the same rendering. The fact that it will no longer be updated could be a problem. Just try our new update later and see if this still happens. Otherwise: Colored Lights was never a really good mod.

**Comment by ghost** [comment]
Again, unfortunately update didn't helped, including changing texture binding option config.

Anyway, thank you for your attention, and good luck with your rewrite and TiM :)

**Comment by EternalBlueFlame** [comment]
Yeah if it's not fixed in 012 it's most likely an issue with CLC not properly ending GL calls, or attempting to do rendering on a thread separate from the actual rendering thread, so the results are gonna be a mixed bag of fruits.

**Comment by cool9535** [comment]
Now, I want to comment on this, if you just want colored lights for creation of train signals I would highly suggest using the Project Red Integration and Project Red Lightning instead of colored lights, you will also be able to have smaller lamps like ones that doesn't take up an entire block of space, they are called fixtures and I use them in my modpack too and it is fully compatible with TC :)
