### ISSUE TITLE
EMD F3/F7 B-unit Maybe bug?

### ISSUE THREAD

**Issue by xNccPlay** [EternalBlueFlame/Traincraft-5#335]
![emd bug](https://user-images.githubusercontent.com/1348874/31706810-87937632-b3ea-11e7-8f81-19e582dbea12.png)

The EMD F3 B-unit and EMD F7 B-unit has the wrong mass (negative? lol...maybe only in description)

**Comment by NitroxydeX** [comment]
You should have googled first what the b-unit does.
negative mass is correct and the type is correct too. 

A B-Unit is the same as an A-Unit (EMD F7) just without the Cab. It's a second loco to make it easier to pull heavy load. Since our system doesn't support B-Units like they act in reallife we reduce the mass of the whole train to emulate this.

But you need to fill it up with diesel otherwise it's not working.

**Comment by HydrogenC** [comment]
Could we add 2 B-Units?

**Comment by MggMuggins** [comment]
I assume that B-units will be supported with the rewrite?

**Comment by EternalBlueFlame** [comment]
The rewrite will have more proper B-units, but for now the current ones in 013 work pretty well. More could be added for 014 if someone wants to make them.

**Comment by MggMuggins** [comment]
But will the Physics system support them without having to use weird hacks like this to make it work well?

**Comment by EternalBlueFlame** [comment]
yeah, the physics in the rewrite will allow it to properly effect the train's functionality as if it's another train.
it would still get managed like a tanker (for ease of use), but it wont be so hacky as to need the weight to be negative.
