### ISSUE TITLE
Train lights?

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#340]
would it be possible to modify optfines code for dynamic lighting to use it in trains as headlights? like press "L" for "Lights" if this would be possible please let me know.

**Comment by NitroxydeX** [comment]
This feature is already implemented for the rewrite.

**Comment by traso56** [comment]
also to note i succesfully added some trains using the dynamic lights mod and they in fact emit light but only looks okay with passenger carts, in locos it wouldn't look like you expect i.e. not a lot of light to the front

**Comment by EternalBlueFlame** [comment]
yeah the issue is you need to add dynamic light from a specific part of the geometry to get the perfect spot (like in the rewrite, or at least in an upcoming update of it), not the entity itself, because if you show the hitboxes (CTRL + B) you can see the entity position isn't optimal unless you do it from the bogie, and even then it's questionable.
