### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HydrogenC** [EternalBlueFlame/Traincraft-5#341]
This suggestion is for 1.7.10

Please add crossovers such as these:
https://upload.wikimedia.org/wikipedia/commons/e/e3/%C3%9Cberleitstelle_Richthof.JPG
https://upload.wikimedia.org/wikipedia/commons/d/d6/Ttc-keele-crossing.jpg

Please add Y switches.

Maybe 45° tracks and switches?

Bigger parallel switches (like 6 blocks wide).

Please add more electric locomotives.

Maybe overhead lines (if possible)?

This mod is for reference:
https://minecraft.curseforge.com/projects/zora-no-densha

**Comment by NitroxydeX** [comment]
just to comment this:

Tracks got it's own issue ticket as you already found out
Overhead lines are already in: You can use every pipe that can transfer Redstone Flux as overhead wire (but not buildcraft due to their implementation of RF)

ZnD for reference compared to Traincraft is just... weird. We're already working with the ZnD-Dev but both mods do have two complete different goals.
