### ISSUE TITLE
My first try at a model.

### ISSUE THREAD

**Issue by TrainsAndThings** [EternalBlueFlame/Traincraft-5#366]
so i decided to try my hand at modeling so i decided to make a wig-wag signal after asking mazaradie what he tought i should do, he gave me two ideas, a wig-wag or a remake of a current thing but i tought i wasent skilled enough for a remake so i made this. 

[New folder (2).zip](https://github.com/EternalBlueFlame/Traincraft-5/files/1701763/New.folder.2.zip)

**Comment by EternalBlueFlame** [comment]
Denied on the account we got confirmation the base of the model was from a user we banned from contributing, on top of receiving help designing it from said user.
I had suspicious of it from the get-go because I heard he was making the same type of signal.
Couldn't get anyone to follow up on the suspicions, so reply was delayed.
