### ISSUE TITLE
coach linkage problem

### ISSUE THREAD

**Issue by minningguyteen2** [EternalBlueFlame/Traincraft-5#383]
IF YOU THINK THIS ISSUE HAS ALREADY BEEN DISCUSED... You may close this thread.

whenever i couple up any coach to any locomotive this happens: ![2018-04-28_11 35 34](https://user-images.githubusercontent.com/28766861/39395700-874559da-4ad9-11e8-9078-0126279594c2.png)

when i delete the locomotive that i was using this happens:
![2018-04-28_11 37 00](https://user-images.githubusercontent.com/28766861/39395725-1a540fe6-4ada-11e8-86d1-77df5998bd8c.png)

**Comment by EternalBlueFlame** [comment]
The IC4 was intentionally disabled due to a number of linking issues from it's size (additionally the model wasn't exactly up to par on quality).
We would have removed it from the creative menu but that would have caused problems in other systems, TC doesn't like things being removed.

Additionally it appears your linked transports go beyond your chunkloaded distance, there's a bug in the recent build that makes the mod fail to force chunkloading, so that's something to keep in mind. (we're at least trying to have that problem fixed in the next release)

**Comment by minningguyteen2** [comment]
this one happened whilst in the chunkloaded distance funnily enough:
![2018-04-27_12 42 35](https://user-images.githubusercontent.com/28766861/39399259-9562f304-4b12-11e8-9ff8-16a53251a088.png)

**Comment by EternalBlueFlame** [comment]
Very strange.....
I'll go over the linking code related to the error message and see if i can maybe give it some backup plan if it can't hold the link for whatever reason.

**Comment by TrainsAndThings** [comment]
what if the car checked for a engine and if there was  not one linked to it, it would apply some type of "emergency" brake? like the train has a air hose connected to a EOT device and if the EOT device gets too far from the engine it would automatically apply the brakes.

**Comment by EternalBlueFlame** [comment]
that would require a lot more advanced checking and data caching than the mod has, additionally it wouldn't fix the problem. only stop you when it happens.
