### ISSUE TITLE
Rails not visible

### ISSUE THREAD

**Issue by Treeminer** [EternalBlueFlame/Traincraft-5#395]
Hello there,

when I load a save or start a new game, sometimes the rails are not visible. When I replace the pieces, the problem is gone. I don't know if thats a new bug, but how does that happen?

![2018-06-09_19 00 21](https://user-images.githubusercontent.com/33221332/41194161-96dff5f8-6c17-11e8-9bb0-cef29779ec5f.png)

**Comment by EternalBlueFlame** [comment]
It can happen if the rail loses it's NBT data due to a saving error, although i have been getting recent bug reports of semi-transparent tracks that's related to a tile entity in the nearby area that doesn't properly end it's GL calls.

The NBT bug we can't do anything about till the rewrite, and even then it's questionable due to various unreliable server hosting programs like thermos, kcauldron, and even forge itself.

The partially transparent bug however we are coming out with a fix for in 017.
