### ISSUE TITLE
Electric Locos not Accepting IC2 Batteries 

### ISSUE THREAD

**Issue by maas124** [EternalBlueFlame/Traincraft-5#396]
Hi, 
So electric locos refuse to load from IC2 batteries, this not being the case for the 1.6.4 releases. Is this something unintended or is it deliberately done?
cheers
Maas

**Comment by EternalBlueFlame** [comment]
IC2 support was removed in 1.7.10 due to some compatibility issues with their 1.7 API.
With the rewrite we will be looking into adding support again since all our newer systems will be vastly simplified, but no promises.

As an alternative, any items that hold an RF charge should work, and redstone of course.
You can also build thermal dynamics pipes overhead of the trains. I've had reports mekanism pipes work as well.
The main issue with pipes is that they have to be able to discharge without being connected to a block, which only a couple support.
We will be adding our own overhead wires and batteries in the rewrite to help make this stuff more reliable for use with other mods.
