### ISSUE TITLE
Trains and cars get stuck going up sloped rails , Compile Aug 3 2018

### ISSUE THREAD

**Issue by Tsoccerguy3** [EternalBlueFlame/Traincraft-5#406]
Compile Aug 3 2018
Engines half way up a slope turn around in opposite direction or get stuck . cars just get stuck

Will investigate this bug later

**Comment by EternalBlueFlame** [comment]
Its an old pathfinding bug due to inaccurate calculations with the slopes and sloppy pathfinding.

It's fixed in the rewrite but I have no plans on fixing it in the port. More work than I think it's worth, when a rewrite is later in the year.

But if you or someone else wants to fix it, feel free to do so.

**Comment by Tsoccerguy3** [comment]
This is something else . My compile from July 20 2018 , Traincraft-4.4.0_016 , does not have this problem 
 something has broke in the last 14 days

**Comment by Tsoccerguy3** [comment]
I'll go through the code and see what happened

**Comment by NitroxydeX** [comment]
nothing changed inside the RollingStock since 18 May.

**Comment by Tsoccerguy3** [comment]
The problem starts with 9c1701f3afaeab31c6a2c8a022f370470fe743a9
reverting back to previous code fixes issue
ill take closer look later
