### ISSUE TITLE
Train Max Speed is Now Treated As m/s Rather Than km/hr

### ISSUE THREAD

**Issue by Doublehelix13** [EternalBlueFlame/Traincraft-5#429]
I've noticed that, now that 018 is out, locomotives are going  way over their maximum speed.  For example, the VL10, with is supposed to have a max speed of 100 km/h, now maxes out at 360 km/hr.  The small steam locomotive, whose max speed is supposed to be 45 km/h, now maxes out at 162 km/hr.

I did some math and found that these new max speeds are what the max speeds would be if they were in meters per second rather than kilometers per hour.  For example, considering the VL10 again:

100 m/s * 1/1000 km/m * 60 s/min * 60 min/hr = 360 km/hr.

In addition, attaching carts to a locomotive has no effect on its maximum speed.  A VL10 carrying over 300 tons was still able to go 360 km/hr.

**Comment by EternalBlueFlame** [comment]
yeah, the calculation wasn't translated properly between the actual max speed and the calculated movement speed, they are actually moving at the noted speed in the gui, this was fixed in a more recent update for 019, which I just now realized didn't get pushed to git, I'll have to deal with that first thing tomorrow.
