### ISSUE TITLE
Death message showing

### ISSUE THREAD

**Issue by VioletWyvern** [EternalBlueFlame/Traincraft-5#457]
At now, If someone's named entities was crush by the train, It's only showing _**"? was ran by the train"**_ 
(The ? was even not showing at the message)

And I can't find any ways to change the death message in the lang files,  Might have been forgotten for a while...

**Comment by NitroxydeX** [comment]
death message are not changeable by language files atm.
But nice heads up for named entities.

will check that

**Comment by EternalBlueFlame** [comment]
The name system is designed to only apply to players, that message shouldn't even show up at all for mobs, named or otherwise.
I'll push a change now to fix this issue by adding support for named mobs.

As for the language files, nitro is correct, due to the design they are not reliably changeable by language files currently.
