### ISSUE TITLE
Alpha error message when using Traincraft 4.4.1_020-alpha after January, 31 2019

### ISSUE THREAD

**Issue by tonimark** [EternalBlueFlame/Traincraft-5#461]
I can't run train craft because Minecraft says that I got expired versions while on curse forge this is actually the latest uploaded file I use train craft:4.4.1_020-alpha on curse forge and says me that is expired I checked the told link and i didn't see newer versions from what i use take a look:
![37](https://user-images.githubusercontent.com/17166550/52123728-a41a0d80-262f-11e9-836a-adcac547d0fa.png)

**Comment by cool9535** [comment]
You are using the Alpha build of Trancraft 020 which expired yesterday, you must go back to 019 or wait for the actual 020 release

**Comment by NitroxydeX** [comment]
If you would read the error-message carefully you would notice that it explicit states "RELEASE-BUILD".

Release-builds are marked green and with a "R" on curseforge. 020-alpha (the name already states it) was marked as alpha (big "A") in bright RED.
The alpha is removed now anyway so download 019 or wait for upcoming 020 release.

There is a reason why alpha-builds aren't distributed through the curseforge network. You can't even use it in the twitch launcher.

**Comment by tonimark** [comment]
damn it I tried with previous 019- and I got a crash at initializing i will post a issue later

**Comment by Tsoccerguy3** [comment]
The crash could be due to a feature in the Alpha , that is not in 019 . This is why it's not a good idea to move to a test build. Back up your world don't run the 019 . The area last logged into has minor corruption  .  , Wait for a 020 Release . Alternatively look at error log and remove the entities from the coordinates reported in the error log with mcedit.
