### ISSUE TITLE
MTC crashes Minecraft on init after going back to 019 from 020-alpha - even with no computercraft installed

### ISSUE THREAD

**Issue by tonimark** [EternalBlueFlame/Traincraft-5#462]
my game crashes at initializing when loading a railcraft versions on  019 but when I use the alpha 020 the game seems to initialize fine but here is the crash log at Pastebin:https://pastebin.com/KUu83FuU

**Comment by NitroxydeX** [comment]
This is really weird. This crash shouldn't even happen.

It's complaining about several missing classes that shouldn't load at _ALL_ cause you don't have computercraft installed.

**Comment by EternalBlueFlame** [comment]
020 had some mod detection issues, so they could have loaded in for 020 and for some reason didn't get removed from world when going back to 019.

One potential fix is enabling the "remove erroring tile entities" in your /config/forge.cfg
But either way, it was an _alpha_ for a reason...

**Comment by tonimark** [comment]
@EternalBlueFlame tried your fix but it didn't work

**Comment by tonimark** [comment]
I will try to install computercraft

**Comment by tonimark** [comment]
@EternalBlueFlame  I found out that when I installed computercraft the game works fine. there is like a missing mod that needs to be a present issue

**Comment by NitroxydeX** [comment]
@EternalBlueFlame the crash report indicates that minecraft didn't even started at all. It's failing on the construction part. The world has nothing to do with it here.

@tonimark yeah it works fine because it's complaining about missing computercraft in the crashreport. But it shouldn't do that on mod construction

**Comment by tonimark** [comment]
yeah, but I didn't want computercraft at all why do I need? well the bug causes the traincraft to required another unnecessary mod to work you should fix that by 020 release

**Comment by EternalBlueFlame** [comment]
It's already fixed for the next release.
There were a lot of bugs in 019 due to an optional computercraft module added by one of our contributors.
I still have to wonder why it would be crashing like that....
well the next release isn't too far out anyway.

**Comment by Tsoccerguy3** [comment]
The crash could be due to a feature in the Alpha , that is not in 019 . This is why it's not a good idea to move to a test build. Back up your world don't run the 019 . The area last logged into has minor corruption . , Wait for a 020 Release . Alternatively look at error log and remove the entities from the coordinates reported in the error log with mcedit.

Tony if you have any coding knowledge , to save your world revert , true to false "public static final boolean alpha = false;" . You can also change the date . Then compile . Go into your world and undo anything you did in the Alpha

From Traincraft.java

```
/* Traincraft Alpha checks */
public static final boolean alpha = false;
public static final boolean alpha = true;

public static boolean alphaEnd() {
	Calendar cal = Calendar.getInstance();
	return (cal.get(Calendar.MONTH) == Calendar.JANUARY && cal.get(Calendar.DATE) <= 14);
	return (cal.get(Calendar.YEAR) == 2019 && cal.get(Calendar.MONTH) == Calendar.JANUARY && cal.get(Calendar.DATE) >= 21 && cal.get(Calendar.DATE) <= 31);
}
```

**Comment by NitroxydeX** [comment]
@Tsoccerguy3 Like I wrote posts before: This crash is on INIT not world join. so it doesn't really help.
