### ISSUE TITLE
Add Overhead Lines as needed Decoration

### ISSUE THREAD

**Issue by NitroxydeX** [EternalBlueFlame/Traincraft-5#49]
ENHANCEMENT/IDEA

KillerMapper proposed this in the [MC Forum](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287038-traincraft-4-2-1?comment=3466). It's an Idea to discuss about.

**Comment by maehschaf** [comment]
Definitely a good idea. I think signals as decoration would be cool too!

**Comment by NitroxydeX** [comment]
Signals as decoration? No way. If we provide signals than they are functional.

**Comment by matart0** [comment]
Would be there a difference?

**Comment by 31trainman** [comment]
I think overhead lines should be able to transmit power

**Comment by NitroxydeX** [comment]
@matart0  yes. If it's decoration it just does nothing. It's just a rendered thing. if it's functional it detects trains and so on. ^^

@31trainman well. no. We won't do it. I've described it in the MC Forums why we will never do this. Deal with it.

**Comment by matart0** [comment]
@NitroxydeX thanks... I'm fool, sorry xD

**Comment by maehschaf** [comment]
Well functional signals would be great, but when electric trains only work when there are overheadlines above them (as KillerMapper said) they aren't just "decoration" too, right?

**Comment by NitroxydeX** [comment]
@maeschaf They are just decoration. The Train would just check if Block Overheadlines is over it.

**Comment by 31trainman** [comment]
1.2.5 had working overhead lines for a time

**Comment by NitroxydeX** [comment]
@31trainman and? That doesen't mean it was good. It isn't good to load every chunk with overhead wires. So we won't provide functionality to it.

**Comment by 31trainman** [comment]
Perhaps the overhead lines store power and act like a battery so they aren't needing to chunkload a lot

**Comment by EternalBlueFlame** [comment]
1.2.5 was a _Completely_ different API for forge.

Now there are only a couple ways to do this with it actually working, and neither of them are very good.
1: The same way as pipes in buildcraft transport items (we all know the problems they have over vast distances).
2: The same way powered tracks work in the base game (which would be more realistic but a lot of hassle for the end user)

Either way it requires a whole new track system, or close enough, because the current one barley works for the features it has now.

**Comment by NitroxydeX** [comment]
@31trainman but you would need to charge them if they are empty. You don't want to charge 6000 Blocks Overheadlines.
@EternalBlueFlame That's why the Original Idea is based on detecting the Block/Tile. You would only need to do it in the Electric Train Class.

**Comment by EternalBlueFlame** [comment]
hmm, in that case if it's just a block over the rails, we used to have an option to use wires from ic2, theoretically, couldn't we use the same kind of idea for build craft pipes to get the result we want?
it would be an easy solution. although the average user would need mekanism or Galacticraft for battery blocks every so often, due to issues with BC pipes.
