### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Maks-Haswell** [EternalBlueFlame/Traincraft-5#510]
https://hastebin.com/vumuropuci.sql

**Comment by EternalBlueFlame** [comment]
In your /config/forge.cfg file be sure to enable removal for tile entities and entities, here's an example

`B:removeErroringEntities=true`
`B:removeErroringTileEntities=true`

Minor patches are being made with the next release to help prevent some of these errors, many of which have been around since 1.6, but unfortunately it should be expected the issue will rear up from other places as well. It's easier and more reliable for users to just change the config than worry about helping track these down. There's a rewrite in the works anyway.

**Comment by Maks-Haswell** [comment]
I had it turned on but it did not help

**Comment by EternalBlueFlame** [comment]
that's a first....

The issue is caused by a corrupted tile entity, if enabling those settings does not fix the issue then the offending rail tile entity would have to be removed manually through something like MCEdit.

The only other options would be to wait for the next release, which, given our messy development schedule, I wouldn't advise. And to compile the git source yourself, but that will likely come with it's own issues as there are a few changes not fully tested yet.

**Comment by Maks-Haswell** [comment]
In general, we will wait when you do an update and fix many errors =)
