### ISSUE TITLE
Retard alert

### ISSUE THREAD

**Issue by EwyBoy** [EternalBlueFlame/Traincraft-5#516]
https://github.com/EternalBlueFlame/Traincraft-5/blob/f75860f4a3df02c5a5703958dfdcaa68b0379533/src/main/java/train/common/core/handlers/WorldEvents.java#L93

**Comment by Fexcraft** [comment]
Yes, correctly one should check for the player join event, it's more efficient and direct.

**Comment by FinnT730** [comment]
It is not just that. There is code that blacklist players to stop them from playing with the mod.

**Comment by infiniteblock** [comment]
This is a violation of Cf and the EULA.

You banned me because im toxic for pointing this out.. check out the last guy who did this and was banned from CF
https://www.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/

Now check out the verbal abuse to me and about my children from eternal... seriously what is this developer upto this is disgusting!
https://media.discordapp.net/attachments/619077509320933386/711496530678251540/eternal1.png?width=887&height=501

https://media.discordapp.net/attachments/619077509320933386/711496522486775818/tc.png?width=887&height=501
