### ISSUE TITLE
Fix spelling of "been" to not annoy people called Ben.

### ISSUE THREAD

**Issue by Lordmau5** [EternalBlueFlame/Traincraft-5#518]
There is a typo in the exception that's being thrown if one of the 2 UUIDs matches.

It states `You have ben banned` instead of `You have been banned`.

I'm sure this could annoy a bunch of people called Ben as they might feel targeted by this typo.

I myself am not called Ben, but I hope this will be addressed in a future version of the mod so they can feel at ease knowing that they aren't targetted anymore.

https://github.com/EternalBlueFlame/Traincraft-5/blob/f75860f4a3df02c5a5703958dfdcaa68b0379533/src/main/java/train/common/core/handlers/WorldEvents.java#L99

**Comment by Lordmau5** [comment]
I've just noticed that I linked to an older version of the file in the issue, my apologies.

The newer one apparently differentiates between different cases?

I'll get a PR up in a few minutes that will address this so all the Bens on this planet can rest at ease.

https://github.com/EternalBlueFlame/Traincraft-5/blob/1.7/src/main/java/train/common/core/handlers/WorldEvents.java#L131

**Comment by infiniteblock** [comment]
This is a violation of Cf and the EULA.

You banned me because im toxic for pointing this out.. check out the last guy who did this and was banned from CF
https://www.reddit.com/r/feedthebeast/comments/g3fekk/looks_like_plus_tic_and_all_of_landmasters_mods/

Now check out the verbal abuse to me and about my children from eternal... seriously what is this developer upto this is disgusting!
https://media.discordapp.net/attachments/619077509320933386/711496530678251540/eternal1.png?width=887&height=501

https://media.discordapp.net/attachments/619077509320933386/711496522486775818/tc.png?width=887&height=501
