### ISSUE TITLE
Grafics bug

### ISSUE THREAD

**Issue by makecodemaster** [EternalBlueFlame/Traincraft-5#664]
i have a problem with traincraft mod. If i play 1.7.10 with traincraft some entity are black and if i place a block chunk where are this block placed are start for some seconds blink in random colors. and trains if are placed on rail are black too. I can this fix please?

**Comment by EternalBlueFlame** [comment]
These have been happening on a large scale recently. we believe they are related to a recent intel driver update.
There are some changes posted for the next TCCE release, but we're not yet sure if we can fix it, or if we have to wait for the drivers themselves to get fixed.

**Comment by makecodemaster** [comment]
ok

**Comment by makecodemaster** [comment]
yes, but in the forge 1.12.2 still all working in normal

**Comment by EternalBlueFlame** [comment]
The entire rendering system for TC5 has been vastly reworked as compared to TCCE. And it's not going to be a simple replacement to backport.

In addition to that, 1.12 and 1.7.10 are very different platforms of the game itself, so it may be something from the game, and i have no way of knowing because no one with the issue will test the 1.7 version of TC5.
