### ISSUE TITLE
I suggest adding the possibility of draining the liquid from the barrels

### ISSUE THREAD

**Issue by GhostUkraine** [EternalBlueFlame/Traincraft-5#686]
I suggest adding the possibility of draining the liquid from the barrels HBM NTM

**Comment by happyburger23** [comment]
Unless you're talking about a different thing, barrels aren't in this mod.

**Comment by GhostUkraine** [comment]
> Unless you're talking about a different thing, barrels aren't in this mod.

I'm talking about tank-wagon

**Comment by happyburger23** [comment]
Then you'll want Railcraft which does have loaders/unloaders. Buildcraft also compliments it.

**Comment by TheVitya2127** [comment]
NTM has a slightly different fluid system. Not forgefluid.

**Comment by EternalBlueFlame** [comment]
Forge's fluid system is an API.
There's no reason NTM, which appears to still be actively developed, couldn't append support for it to their already existing systems.

There are plans to add our own fluid loaders and unloaders in the not-so-near-future, but they will also use the forge APIs because it's the standardized method for mods to be able to universally support each other.

I don't want to come off as rude or dismissive, but it's a standardized system that dang near everyone uses, at this level of a problem it's not a "we should support them" it's a "they should support everyone else"

The TiM branch used a custom fluid system as well, with support for forge fluids appended.
They are more than welcome to take what they need from it and reverse-engineer it to their use case.
[https://github.com/EternalBlueFlame/Traincraft-5/tree/1.7-TiM](https://github.com/EternalBlueFlame/Traincraft-5/tree/1.7-TiM)

They are also more than welcome to @ me on discord if they have any questions or run into problems.

**Comment by TheVitya2127** [comment]
The NTM uses a different fluid system for optimization

**Comment by EternalBlueFlame** [comment]
As did I in the linked source, but the forge API can still be appended so it can support other mods.

**Comment by TheVitya2127** [comment]
There are too many fluids in NTM for this to be easily implemented (let alone the ability to create custom fluids)

**Comment by EternalBlueFlame** [comment]
Super class inheritance. Write it once, everything that extends the super will just have support.

Worst case scenario where you're extending a vanilla class, you have to make a new class extending the same vanilla class, add the functionality to that, then have all the other classes extend the new one instead.
that brings it down to just one extra line of code per class, plus the API stuff.
