### ISSUE TITLE
Traincraft for MAC

### ISSUE THREAD

**Issue by lEagles22** [EternalBlueFlame/Traincraft-5#687]
I am having trouble adding traincraft as resource pack in Minecraft on Mac

**Comment by happyburger23** [comment]
Mods are not resourcepacks. You need Forge for 1.7.10, and a mods folder.

**Comment by lEagles22** [comment]
oh, how do you do that?

**Comment by EternalBlueFlame** [comment]
There's a number of ways, default is just installing forge itself, then putting the traincraft jar file in the "mods" folder of the install:
[https://files.minecraftforge.net/net/minecraftforge/forge/index_1.7.10.html](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.7.10.html)

there's also modpack loaders which give you pre-setup installs for entire mod sets, typically we recommend technic:
[https://www.technicpack.net/modpacks?q=traincraft](https://www.technicpack.net/modpacks?q=traincraft)

There's also curseforge, although it's not fully supported because their client is known to be unreliable.
[https://www.curseforge.com/download/app](https://www.curseforge.com/download/app)
